openapi: 3.0.0

info:
  title: "Beer App REST API"
  description: "API for interacting with Beer App"
  version: "1.0.0"

server:
  - url: "/api"

components:
  schemas:
    Beers:
      type: object
      required:
        - name
      properties:
        beer_id:
          type: integer
        name:
          type: string
        manufacturer:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        availability:
          type: string
        gf_or_gr:
          type: string

paths:
  /api/beers:
    get:
      tags:
        - "Beers"
      summary: "Return all beers in the database"
      responses:
        "200":
          description: "Successfully read all beer info"

  /api/beers/{beer_id}:
    get:
      tags:
        - "Beers"
      summary: "Get one beer"
      parameters:
        - in: path
          name: beer_id
          schema:
            type: integer
          required: true
          description: Numeric ID of beer to get
      responses:
        "200":
          description: "Successfully got one beer"

  /api/beers/{beer_id}/encounters:
    get:
      tags:
        - "Encounters"
      summary: "Get all encounters for given beer ID"
      parameters:
        - in: path
          name: beer_id
          schema:
            type: integer
          required: true
          description: Numeric ID of beer to get encounters for
      responses:
        "200":
          description: "Successfully got encounters for the beer"

  /api/beers/test_1:
    get:
      tags:
        - "Beers"
      summary: "Test getting beer with beer_id=1"
      responses:
        "200":
          description: "Successfully got one beer"

  /api/all_encounters:
    get:
      tags:
        - "Encounters"
      summary: "Get all encounters in the database"
      responses:
        "200":
          description: "Successfully got all encounters"

  /api/contribute:
    post:
      tags:
        - "Contribute"
      summary: "Test the contribute endpoint"
      requestBody:
        description: "Adds a new beer to the database"
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                manufacturer:
                  type: string
                city:
                  type: string
                state:
                  type: string
                country:
                  type: string
                availability:
                  type: string
                gf_or_gr:
                  type: string
        responses:
          '201':
            description: "Created a new beer in the DB"
