# This is the compose file that builds the containers from the Dockerfiles.
# This file is used for testing, as it incorporates any changes that
# may have been made. For the file that pulls from the registry,
# use docker-compose.yml

services:

  db:
    container_name: beer_db
    build: ./src/database
    ports:
      - "5433:5432"
    networks:
      - beer_app_network
    volumes:
      - beer_app_volume:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beer_app

  api:
    container_name: beer_api
    build: ./src/api
    ports:
      - "8080:8080"
    networks:
      - beer_app_network
    environment:
      DB_HOST: beer_db
      DB_PORT: 5432

  app:
    container_name: beer_app
    build: ./src/app
    ports:
      - "80:8000"
      - "443:8000"
    networks:
      - beer_app_network
    environment:
      API_HOST: beer_api
      API_PORT: 8080

volumes:
  beer_app_volume:
    name: beer_app_volume

networks:
  beer_app_network:
    name: beer_app_network