# This is the compose file that will attempt to fetch container images
# from docker hub before running the containers. It is used on the server
# to quickly deploy the webapp. For the compose file that builds the
# containers and uses the new builds, use docker-compose-build.yml

services:

  db:
    container_name: beer_db
    image: alexgarnett/gfreebeerme:beer_db
    restart: always
    ports:
      - "5433:5432"
    networks:
      - beer_app_network
    volumes:
      - beer_app_volume:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beer_app

  api:
    container_name: beer_api
    image: alexgarnett/gfreebeerme:beer_api
    ports:
      - "8080:8080"
    networks:
      - beer_app_network
    environment:
      DB_HOST: beer_db
      DB_PORT: 5432

  app:
    container_name: beer_app
    image: alexgarnett/gfreebeerme:beer_app
    ports:
      - "80:8000"
      - "443:8000"
    networks:
      - beer_app_network
    environment:
      API_HOST: beer_api
      API_PORT: 8080

volumes:
  beer_app_volume:
    name: beer_app_volume
    #external: true

networks:
  beer_app_network:
    name: beer_app_network