name: GFreeBeerMe
on: [push]

jobs:
  test_application:
    name: Test application
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Start containers
      run: docker-compose -f "docker-compose-build.yml" up -d --build
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down

  push_to_registry:
    name: Push Docker images to Docker Hub
    needs: test_application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push database
        uses: docker/build-push-action@v5
        with:
          context: ./src/database
          file: ./src/database/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/gfreebeerme:beer_db

      - name: Build and push api
        uses: docker/build-push-action@v5
        with:
          context: ./src/api
          file: ./src/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/gfreebeerme:beer_api

      - name: Build and push app
        uses: docker/build-push-action@v5
        with:
          context: ./src/app
          file: ./src/app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/gfreebeerme:beer_app

  deploy_app:
    name: Deploy app to DigitalOcean
    needs: [test_application, push_to_registry]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy compose file to remote machine
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: docker-compose.yml
          target: /root/

      - name: Copy schema.sql to remote machine
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: ./src/database/schema.sql
          target: /root/src/database/

      - name: Update and start containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }} &&
            docker compose down &&
            docker rmi $(docker images -a -q) &&
            docker volume rm beer_app_volume &&
            docker compose up --detach
