name: GFreeBeerMe
on: [push]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install requirements
      run: pip install -r requirements.txt
      
    - name: Run test
      run: pytest

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
