name: GFreeBeerMe
on: [push]

jobs:
  test_application:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down

  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push database
        uses: docker/build-push-action@v5
        with:
          context: src/database
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/gfreebeerme:beer_db

      - name: Build and push api
        uses: docker/build-push-action@v5
        with:
          path: src/api
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/gfreebeerme:beer_api

      - name: Build and push app
        uses: docker/build-push-action@v5
        with:
          path: src/app
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/gfreebeerme:beer_app
